add_test( [==[Handles single point]==] /Users/abhmulla/Desktop/Synolo/test_lib/createkdtree_test [==[Handles single point]==]  )
set_tests_properties( [==[Handles single point]==] PROPERTIES WORKING_DIRECTORY /Users/abhmulla/Desktop/Synolo/test_lib)
add_test( [==[Handles two points correctly]==] /Users/abhmulla/Desktop/Synolo/test_lib/createkdtree_test [==[Handles two points correctly]==]  )
set_tests_properties( [==[Handles two points correctly]==] PROPERTIES WORKING_DIRECTORY /Users/abhmulla/Desktop/Synolo/test_lib)
add_test( [==[Handles three points with median root]==] /Users/abhmulla/Desktop/Synolo/test_lib/createkdtree_test [==[Handles three points with median root]==]  )
set_tests_properties( [==[Handles three points with median root]==] PROPERTIES WORKING_DIRECTORY /Users/abhmulla/Desktop/Synolo/test_lib)
add_test( [==[Removes duplicates during construction]==] /Users/abhmulla/Desktop/Synolo/test_lib/createkdtree_test [==[Removes duplicates during construction]==]  )
set_tests_properties( [==[Removes duplicates during construction]==] PROPERTIES WORKING_DIRECTORY /Users/abhmulla/Desktop/Synolo/test_lib)
add_test( [==[KdTree construction matches research paper example]==] /Users/abhmulla/Desktop/Synolo/test_lib/createkdtree_test [==[KdTree construction matches research paper example]==]  )
set_tests_properties( [==[KdTree construction matches research paper example]==] PROPERTIES WORKING_DIRECTORY /Users/abhmulla/Desktop/Synolo/test_lib)
set( createkdtree_test_TESTS [==[Handles single point]==] [==[Handles two points correctly]==] [==[Handles three points with median root]==] [==[Removes duplicates during construction]==] [==[KdTree construction matches research paper example]==])
